#!/bin/bash

if [ $EMBOX_GCC_ENV ] && [ -f $EMBOX_GCC_ENV ]; then
	. $EMBOX_GCC_ENV
else
	echo "No EMBOX_GCC_ENV is set" >&2
	exit 1
fi

cmd=$(basename $0)
case $cmd in
	*-clang)   C_CXX_FLAGS="$EMBOX_IMPORTED_CPPFLAGS $EMBOX_IMPORTED_CFLAGS";;
	*-clang++) C_CXX_FLAGS="$EMBOX_IMPORTED_CPPFLAGS $EMBOX_IMPORTED_CXXFLAGS";;
	*)     echo "Unknown flags for $cmd"; exit 1;;
esac

COMPILER=clang
case $EMBOX_GCC_LINK in
	full)
					ARG_LINE="$C_CXX_FLAGS $EMBOX_IMPORTED_LDFLAGS $EMBOX_IMPORTED_LDFLAGS_FULL -target armv7em-none-eabi";
					COMPILER="arm-none-eabi-gcc -mthumb -mlittle-endian -march=armv7e-m -mcpu=cortex-m4 -msoft-float"
		;;
	*)
	       	ARG_LINE="$C_CXX_FLAGS $EMBOX_IMPORTED_LDFLAGS -Wl,-r"
		;;
esac


case " $@ " in
	*" -c "*) ARG_LINE="$C_CXX_FLAGS";;
	*" -E "*) ARG_LINE=;;
	*" -shared "*) echo "Can't build shared objects"; exit 1;;
	*" -lm "*) echo -e "\n\ERROR!!! Linking with libm\n\n"; exit 1;;
	*" -l"*) echo -e "\n\nWARNING!!! You're linking something with it\n\n";;
esac

ARG_LINE="$ARG_LINE $EMBOX_IMPORTED_CPPFLAGS"
PWD_ARG_LINE="$(for i in $ARG_LINE; do echo ${i/$PWD/.}; done)"
# echo "$EMBOX_CROSS_COMPILE${cmd#arch-embox-} $@ $PWD_ARG_LINE" >&2

arr=(`echo $@ | xargs`)
POSTARGS=""
#POSTARGS="-D'__strong_alias(alias, sym)=__asm__(\".global \" #alias \"\\n\" #alias \" = \" #sym);' $POSTARGS"
#POSTARGS=$'-D\'__strong_alias(alias, sym)=__asm__(\".global \" #alias \"\\n\" #alias \" = \" #sym);\'' ""
arr_pwd_arg_line=(`echo $PWD_ARG_LINE | xargs`)

if [ "$EMBOX_GCC_LINK" = "full" ]; then

	for ((i=1; i<=${#arr_pwd_arg_line[@]}; i++ )); do
		if [ "${arr_pwd_arg_line[$i]}" = "-target" ]; then
			arr_pwd_arg_line[$i]=""
			arr_pwd_arg_line[$((i+1))]=""
		fi
	done
else
	for ((i=1; i<=${#arr[@]}; i++ )); do
		declare -x res=`echo "${arr[$i]}" | sed -n "s/-march\=\(.*\)/\1/p"`

		if [ "x$res" != "x" ]; then

			case "$res" in
			arm)
				#echo "AAAAAAAAAAAAAAAA";
				if [ "$EMBOX_GCC_LINK" = "full" ]; then
					POSTARGS="$POSTARGS -target arm---"
				else
					POSTARGS="$POSTARGS -target $res---"
				fi
				;;
			armv7em)
				#echo "BBBBBBBBBBBBBBBBB";
				if [ "$EMBOX_GCC_LINK" = "full" ]; then
					POSTARGS="$POSTARGS -target arm---"
				else
					POSTARGS="$POSTARGS -target $res---"
				fi
				;;
			esac
			arr[$i]=""
		fi
	done
fi
#echo $( IFS=$' '; echo "${arr_pwd_arg_line[*]}" )

PWD_ARG_LINE=$( IFS=$' '; echo "${arr_pwd_arg_line[*]}" )

$COMPILER $sobaka \
	$PWD_ARG_LINE \
	$POSTARGS -include sys/cdefs.h
exit $?
